# Generated by Django 3.2.7 on 2023-04-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_users'),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='event_id',
        ),
        migrations.AddField(
            model_name='pay',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
