# Generated by Django 3.2.7 on 2023-04-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0002_auto_20230411_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRelatedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pay.pay')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
