# Generated by Django 3.2.7 on 2023-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_payrelateduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='created_at',
            field=models.DateTimeField(default='2023-05-15T22:21:37.909927'),
        ),
        migrations.AddField(
            model_name='payrelateduser',
            name='created_at',
            field=models.DateTimeField(default='2023-05-15T22:21:37.910572'),
        ),
    ]
