# Generated by Django 3.2.7 on 2023-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20230515_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='created_at',
            field=models.DateTimeField(default='2023-05-15T22:41:16.566023'),
        ),
        migrations.AlterField(
            model_name='payrelateduser',
            name='created_at',
            field=models.DateTimeField(default='2023-05-15T22:41:16.566665'),
        ),
    ]
