version: "3.8"

services:
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/default.conf
    depends_on:
      - web

  db:
    image: mysql
    restart: always
    ports:
     - ${DB_PORT}:${DB_PORT}
    hostname: dbserver
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_USER: root
      MYSQL_USER: ${DB_USER}
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - '${DB_PORT}'
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${WEB_PORT}
    volumes:
      - .:/code
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
  

volumes:
  mysql_data: