# Generated by Django 3.2.7 on 2023-05-16 04:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='イベント名')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 5, 16, 13, 6, 48, 802624))),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='支払い名')),
                ('amount_pay', models.IntegerField(default=0, verbose_name='支払い金額')),
                ('created_at', models.DateTimeField(default='2023-05-16T13:06:48.803651')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_model.event')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayRelatedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default='2023-05-16T13:06:48.803832')),
                ('pay', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_model.pay')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_pay', models.IntegerField(default=0, verbose_name='支払い金額')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 5, 16, 13, 6, 48, 803050))),
                ('adjust_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pay_user', to=settings.AUTH_USER_MODEL)),
                ('adjusted_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paid_user', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_model.event')),
            ],
        ),
    ]
