# Generated by Django 3.2.7 on 2023-06-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('request_user', 'requested_user')},
        ),
    ]
