# Generated by Django 3.2.7 on 2023-05-16 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 20, 58, 46, 83403)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 20, 58, 46, 82921)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 20, 58, 46, 84013)),
        ),
        migrations.AlterField(
            model_name='payrelateduser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 20, 58, 46, 84230)),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 5, 16, 20, 58, 46, 84390))),
                ('user_1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
