# Generated by Django 3.2.7 on 2023-05-17 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0002_auto_20230516_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='approval',
            field=models.IntegerField(default=0, verbose_name='承認'),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 19, 18, 52, 451076)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 19, 18, 52, 450637)),
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 19, 18, 52, 452035)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 19, 18, 52, 451678)),
        ),
        migrations.AlterField(
            model_name='payrelateduser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 19, 18, 52, 451862)),
        ),
    ]
