# Generated by Django 3.2.7 on 2023-06-30 17:14
import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    User = apps.get_model('data_model', 'User')
    for row in User.objects.all():
        row.article_id = uuid.uuid4()
        row.save(update_fields=['user_identifier'])

class Migration(migrations.Migration):
    dependencies = [
        ('data_model', '0003_user_user_identifier'),
    ]

    operations = [
    ]
