# Generated by Django 3.2.7 on 2023-05-17 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0003_auto_20230517_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 16, 14, 881080)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 16, 14, 880628)),
        ),
        migrations.AlterField(
            model_name='friend',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='承認'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 16, 14, 882018)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 16, 14, 881681)),
        ),
        migrations.AlterField(
            model_name='payrelateduser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 16, 14, 881858)),
        ),
    ]
