# Generated by Django 3.2.7 on 2023-05-17 12:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_model', '0004_auto_20230517_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_2',
        ),
        migrations.AddField(
            model_name='friend',
            name='request_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='requested_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 40, 25, 660370)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 40, 25, 659916)),
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 40, 25, 661302)),
        ),
        migrations.AlterField(
            model_name='pay',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 40, 25, 660965)),
        ),
        migrations.AlterField(
            model_name='payrelateduser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 21, 40, 25, 661146)),
        ),
    ]
