# Generated by Django 3.2.7 on 2023-06-30 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0004_auto_20230630_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_identifier',
            field=models.CharField(default=uuid.uuid4, unique=True, max_length=255, verbose_name='ユーザID'),
        ),
    ]
