# Generated by Django 3.2.7 on 2023-07-01 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0005_auto_20230630_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_identifier',
            field=models.CharField(default=uuid.UUID('20dcd07f-671f-4ee1-8a1d-6bced3288fac'), max_length=255, unique=True, verbose_name='ユーザID'),
        ),
    ]
