# Generated by Django 3.2.7 on 2023-05-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0005_auto_20230517_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pay',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payrelateduser',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
