version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install curl
          command: apt-get update && apt-get install -y curl
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/3.8/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: test
          command: docker-compose run python ./manage.py test
      - run:
          name: docker-compose down
          command: docker-compose down