# Generated by Django 3.2.7 on 2023-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default='2023-05-15T22:21:37.908432'),
        ),
    ]
