# Generated by Django 3.2.7 on 2023-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_people',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default='2023-05-15T22:41:16.564605'),
        ),
    ]
