# Generated by Django 3.2.7 on 2023-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjustment', '0002_adjustment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='created_at',
            field=models.DateTimeField(default='2023-05-15T22:41:16.567709'),
        ),
    ]
